[package]
name = "dcl"
build-command = ["cargo", "build", "--release"]

[dist]
targets = ["aarch64-apple-darwin", "x86_64-apple-darwin", "x86_64-unknown-linux-gnu", "aarch64-unknown-linux-gnu", "x86_64-pc-windows-msvc"]
installers = ["shell", "powershell"]
auto-include-files = ["README.md", "LICENSE"]
